name: Mashiro2000-HeyTapTask-sync
on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Mashiro2000-HeyTapTask
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Mashiro2000-HeyTapTask
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Mashiro2000/HeyTapTask.git"
          source_branch: "main"
          destination_branch: "Mashiro2000"
          github_token: ${{ secrets.PAT }}
